### ISSUE TITLE
Author

### ISSUE THREAD

**Issue by 10phillyphan** [puikinsh/newspaper-x#29]
On my author sidebar widget (gnghockey.com), when you click the author their first 2 articles at the top do not show because the first 2 articles are the 2 latest articles from the site.

Basically, the first 2 articles that show on an author page are not articles by the authors but the latest articles from the site which blocks the authors’ latest 2 articles from showing.

**Comment by mahendrapratap4022** [comment]
fixed in the PR https://github.com/ColorlibHQ/newspaper-x/pull/61
