### ISSUE TITLE
Issue with Disqus Plugin

### ISSUE THREAD

**Issue by a-support** [puikinsh/newspaper-x#31]
I don’t know if I express myself correctly, but I would hate to unistall de Disqus ’cause it is not fit especially well in the page.
Atualization: in a forum at Disqus, i got this suggestion:
“There seems to be an issue with the theme, you may want to contact the author of the theme and ask them to make sure that comments go at the end inside this div;
<div class=”row”>
PS. You can use any of the default WP themes to verify it is not an Disqus issue as these place the comment iframe inside the proper HTML section.”

https://colorlib.com/wp/forums/topic/bug-with-the-size-of-the-disqus-plugin/#post-106322

**Comment by giucu91** [comment]
Hello @a-support ,

Please add the following CSS to your website : 

`@media (min-width: 768px){
	#disqus_thread {
	    width: 750px;
	}
}
@media (min-width: 992px){
	#disqus_thread {
	    width: 970px;
	}
}
@media (min-width: 1200px){
	#disqus_thread {
	    width: 1170px;
	}
}
#disqus_thread {
	padding-right: 30px;
    padding-left: 30px;
    margin-right: auto;
    margin-left: auto;
}`
This is a temporary solution until next update when the bug will be fixed.

Have a nice day,
George.

**Comment by a-support** [comment]
Hello there,

Thanks for that solution.

Best Regards,
Support
