### ISSUE TITLE
Problems with notification after theme activation

### ISSUE THREAD

**Issue by giucu91** [puikinsh/newspaper-x#32]
![newspapper](https://user-images.githubusercontent.com/7580330/27957503-77ea580e-6327-11e7-9470-471e14c6a6b9.png)

**Comment by cristian-raiber** [comment]
![3](https://user-images.githubusercontent.com/43263346/50643194-01119d80-0f76-11e9-8494-c3b51255bb70.PNG)
 
no longer an issue
