### ISSUE TITLE
Solution for hyperlink not working in small devices

### ISSUE THREAD

**Issue by vinoddalvi** [puikinsh/newspaper-x#35]
Hyperlink or tag_link in post or pages does not work in small devices like mobile, tab etc.

Issue exists on the page https://colorlib.com/newspaper-x/2017/05/10/aliquet-lorem-pantum/

Related Topic:

https://wordpress.org/support/topic/solution-for-hyperlink-not-working-in-small-devices-newspaper-x-theme/#post-9528172

**Comment by sandman14** [comment]
I'm having this issue too. Any updates on a fix?

**Comment by Thinkfirst1** [comment]
I recently started a page and am also having problems with mobile device hyperlinks on the Newspaper X theme.  The hyperlinks work on desktops but not on ipads or iphones.   My page is www.alternativefact.com.  Any ideas?

**Comment by cristianraiber** [comment]
I'll take a stab at this :)

**Comment by Thinkfirst1** [comment]
Have you had a chance to look at this?

**Comment by NorbertKrupa** [comment]
I also have this issue on mobile

**Comment by wisdomosinachi** [comment]
Am having the same issue here: globainfo.com/

**Comment by wisdomosinachi** [comment]
Can you help me ?
