### ISSUE TITLE
AdSense banners covered by "Loading" message

### ISSUE THREAD

**Issue by rtohme** [puikinsh/newspaper-x#37]
I can see the actual AdSense banners in the background, but they are covered by a semi-transparent cover with the message "Loading". It never did, 
Even after disabling all the plugins in use, I'm still getting the following error on my browser console:
_uncaught exception: TagError: adsbygoogle.push() error: All ins elements in the DOM with class=adsbygoogle already have ads in them._

**Comment by cristianraiber** [comment]
Are you sure you only used the `<ins>` part of your AdSense code? Did you just copy/paste your whole AdSense code?

**Comment by rtohme** [comment]
I just figured this out, there was a couple of widgets where the AdSense code was manually inserted.
Thanks, I'm closing the ticket.
