### ISSUE TITLE
Tagline Hebrew Translation 

### ISSUE THREAD

**Issue by a-support** [puikinsh/newspaper-x#38]
Issue:
As I was starting to design my new website on newspaper X theme I notice that the tagline name is “Blog” and not my Hebrew tagline name for my website.
It happens since I download the newspaper X theme.

https://colorlib.com/wp/forums/topic/tagline-name-show-only-the-name-blog/#post-126387

**Comment by mahendrapratap4022** [comment]
Hi @a-support I checked it using [say what](https://wordpress.org/plugins/say-what/) plugin and it is working just fine to me. It would be great if you can provide a screenshot of it.

Make sure you are following the pattern as guided on this page.
https://plugins.leewillis.co.uk/doc_post/adding-string-replacement/
