### ISSUE TITLE
BBPress compatibility

### ISSUE THREAD

**Issue by a-support** [puikinsh/newspaper-x#39]
Newspaper X theme does not working with bbpress.
The posts seems to show only an excerpt of the post and it is unusable.
Do you have any idea?

PS : on the other hand the Sparkling theme works fine for a forum with bbpress.
https://colorlib.com/wp/forums/topic/bbpress-forum-does-not-work-with-newspaper-x/?view=all#post-126775

**Comment by mahendrapratap4022** [comment]
added bbpress compatibility - https://github.com/ColorlibHQ/newspaper-x/pull/64
