### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sandman14** [puikinsh/newspaper-x#40]
When can we expect the documentation for this theme (newspaper x)?

**Comment by cristianraiber** [comment]
cc @puikinsh

**Comment by puikinsh** [comment]
@sandman14 basics are already covered: https://www.youtube.com/watch?v=mBWXKk1p8Tg&list=PLldz9o1F5Df5SZyFWz_1XyuP2nQPl6vBa

Two more videos will be published later this week, so make sure to subscribe to our YouTube channel. 

For this theme, there won't be any written docs as no one have ever read those anyways :)

**Comment by cristianraiber** [comment]
Marking this as closed, not exactly an issue :)
