### ISSUE TITLE
Archive links won't work on mobile devices

### ISSUE THREAD

**Issue by a-support** [puikinsh/newspaper-x#41]
When an archive is viewed on mobile, only the first 2 links work and the others are inactive.

Source:
https://colorlib.com/wp/forums/topic/archive-and-blog-page-links-to-full-post-dont-work/

**Comment by mahendrapratap4022** [comment]
It is fixed in https://github.com/WPChill/newspaper-x/commit/779d4c62daa20eb06bfee273be9190611fd0baf4 and since we updated the code with WPCill the issue is also fixed in colorlibHQ.
