### ISSUE TITLE
Buggy search widget

### ISSUE THREAD

**Issue by nodarik** [puikinsh/newspaper-x#43]
if we use search even on our demo: https://colorlib.com/newspaper-x/?s=sed+puru

links on the page are not working because they are covered by the buggy search widget, 
all we need is to add this css:

.newspaper-x-blog-sidebar .widget_search {
    display: inline-block;
}

Was reported here:
https://colorlib.com/wp/forums/topic/pages-are-not-clicked-when-searching/

**Comment by cristianraiber** [comment]
@nodarik - interested in doing a pull request with your proposed bug fix?

**Comment by mahendrapratap4022** [comment]
fixed in https://github.com/WPChill/newspaper-x/commit/779d4c62daa20eb06bfee273be9190611fd0baf4 and since WPChill is merged with colorlibHQ it is fixed here also.
