### ISSUE TITLE
Is this an abandoned theme?

### ISSUE THREAD

**Issue by frkn64modding** [puikinsh/newspaper-x#44]
This theme looks great, but it has a lot of issues (especially on mobile devices). I've found some fix codes on your forum and filled up the Additional CSS section on Wordpress with many code.
Are you planning to fix these bugs? Looks like the last update was two years ago...

**Comment by Frkn64** [comment]
###

**Comment by cristianraiber** [comment]
@Frkn64 - wasn't really aware the theme had so many bugs. Will get someone to update it sometime soon (hopefully, this month).

**Comment by frkn64modding** [comment]
**Okay, thanks for fast response!** 
If you need, I can report all bugs I've noticed. I'm looking forward to the new update!

**Comment by cristianraiber** [comment]
@Frkn64 - yes, please report all the bugs you've noticed and we'll address them :)

**Comment by mahendrapratap4022** [comment]
@all we are maintaining all the colorlibHQ themes actively now you can report all the bugs you saw we are updating all the themes now and thanks if you have already reported. We are working hard to resolve all the bugs. (The mobile device bugs are resolved already.)
