### ISSUE TITLE
adsbygoogle.js:35 Uncaught TagError: adsbygoogle.push() error: All ins elements in the DOM with class=adsbygoogle already have ads in them.

### ISSUE THREAD

**Issue by arslanali823** [puikinsh/newspaper-x#46]

**Comment by cristianraiber** [comment]
@arslanali823 - are you sure this is coming from the theme? :) can you please let me know your site's URL and all the plugins you have installed?

**Comment by arslanali823** [comment]
Thanks @cristianraiber for your comment. Issue resolved 👍

**Comment by cristianraiber** [comment]
Glad to hear!
