### ISSUE TITLE
LInks to the demo files

### ISSUE THREAD

**Issue by nodarik** [puikinsh/newspaper-x#56]
Links to the demo installation files are not working:

Posts:https://colorlibvault-divilabltd.netdna-ssl.com/newspaper-x-content.xml
Widgets: https://colorlibvault-divilabltd.netdna-ssl.com/newspaper-x-widgets.wie

Ticket:
https://forums.colorlib.com/t/posts-and-widgets-links-do-not-work/27743

**Comment by mahendrapratap4022** [comment]
updated in - https://github.com/ColorlibHQ/newspaper-x/pull/67
